### ISSUE TITLE
Learner's area bug

### ISSUE THREAD

**Issue by parkclan** [Pieter12345/Styms-Redstone-Server#14]
there is a bug in the /learner area. it crashed my computer and game 5 times. plz fix

**Comment by Pieter12345** [comment]
@parkclan This bug report does not contain a bug description. Please take some care when writing a bug report and include the behaviour you consider as a bug, the expected behaviour in that situation, how to reproduce the bug if possible and details such as a location or anything else that might be related to the bug.
I can say the following based on what you wrote:
- Bugs on our server can not crash your computer. If the Minecraft client crashes your computer, contact Mojang.
- If you mean that the Minecraft client crashed because of something in the Learners area, please include the crash log.
